### ISSUE TITLE
Currently usable?

### ISSUE THREAD

**Issue by brendan-r** [Fuco1/sql-workbench#10]
Hello there,

This project looks very promising! 

However, I can see that it's unreleased. 

Would you recommend someone (me) starting to use it? 

Are there things which are known not to work, to be aware of?

Are you intending to pick up development again in the future, or is it 'on ice' for the time being?

Regardless, thanks for working on it!

**Comment by Fuco1** [comment]
Well, it kind of works for the most part.  It only supports mysql right now (tested on 5.7 and mariadb 10+ clients).  There is hundreds of TODOs because I had so many ideas, but it is usable in day-to-day operations and I have been using it successfully.

The one thing where it breaks completely is if your result set is larger than say 2000 lines and the table has many columns, in that case the Emacs (org) rendering (fontifying) will likely freeze your instance for some time.

The UI is very minimal and there's only 5 or 6 commands, look into `swb-mode-map` for start.

Feel free to try it out and give some feedback :)

**Comment by brendan-r** [comment]
Ahah, I didn't twig the mysql part (I'm only using postgres at the moment). 

Still, thanks for working on it!

**Comment by Fuco1** [comment]
Writing the "connector" is rather simplish... how it works is it just starts the cli client and parses the dump.  Which for the most part just means getting the table output and converting it to an `org-mode` table.

There's some additional extra work with getting the metadata (column types), I'm not sure how postgres client dumps that, if at all).

Just saying if you ever get hungry after some elisp hacking :D

Cheers!
